### ISSUE TITLE
Update TW translations

### ISSUE THREAD

**Issue by mikezliu** [mystocksportfolio/translations#18]
https://www.sfb.gov.tw/en/home.jsp?id=69&parentpath=0,9

**Comment by Nowar** [comment]
I've done some effort on zh-Hant-TW language on #21 , maybe we can give it a try if available. :)
Thanks for your development.

**Comment by mikezliu** [comment]
> I've done some effort on zh-Hant-TW language on #21 , maybe we can give it a try if available. :) Thanks for your development.

Thanks @Nowar, I will get them included in the next release. You can reach out to mike@mystocksportfolio.app and we can upgrade you to premium for helping

**Comment by mikezliu** [comment]
Released: https://github.com/mystocksportfolio/issues/issues/354
